@startuml Activity Diagram: Modell laden
!theme mars

skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam roundcorner 8

skinparam arrow {
    Color #4A90D9
}

start

partition "Test- und Evaluierungsumgebung" {

    :Starten der App durch Benutzer:in;
}


partition "AM-Modell Pipeline" {

    :Modell aus Projektverzeichnis laden;
}


stop

@enduml