@startuml Activity Diagram: Modell-Trainings-Workflow
!theme mars

skinparam defaultFontName Arial
skinparam defaultFontSize 12
skinparam roundcorner 8

skinparam arrow {
    Color #4A90D9
}

start

partition "Vorverarbeitung" {

    :DARIUS-Korpus .tsv Dateien in BinDoc-Format konvertieren;
    :Daten in Trainings- und Test-Split aufteilen;
}

repeat :Modell-Konfiguration festlegen/ändern;

    partition "Training" {
    
        :iteratives Training starten;
        :Evaluation auf Testdaten durchführen;
        :Training stoppen sobald keine 
        Verbesserungen mehr sichtbar sind;
        :Bestes Modell auswählen und speichern;
    
    }

repeat while (mögliche Verbesserungen in der Konfiguration?) is (ja)

:Modell im Projekt ablegen;

stop

@enduml